name: Update Offline Docs

on:
  workflow_dispatch:
  push:
    branches:
      - 'my-docs'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout theos/theos
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Checkout theos/theos.dev
        uses: actions/checkout@v3
        with:
          repository: theos/theos.dev
          path: tmp
          submodules: recursive
          fetch-depth: 1

      - name: Build docs
        run: |
          make -C tmp all
          mkdir -pv docs/assets/
          cp -av tmp/_site/docs/* docs/
          cp -av tmp/_site/assets/*.css docs/assets/
          rm -rvf tmp

      - name: Cleanup broken formatting
        run: |
          sed -i 's/<a href="\/">/<a href=".\/">/g' docs/*.html
          sed -i 's/\/assets\//assets\//g' docs/*.html
          sed -i 's/theos.dev\/docs\//mask/g' docs/*.html # mask https://theos.dev/docs/
          sed -i 's/\/docs\//..\/docs\//g' docs/*.html
          sed -i 's/mask/theos.dev\/docs\//g' docs/*.html # unmask https://theos.dev/docs/
          sed -i 's/ Deployed on <a href="https:\/\/netlify.com">Netlify<\/a>.//g' docs/*.html

      - name: Update docs
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add docs
          git commit -m "[docs] Update offline docs to the latest commit" && git push || echo "No changes were made"
